config/routes.rb
Rails.application.routes.draw do
  get 'univs/search', as: 'search_univs'
  get 'univs/:id/new' => 'posts#new', as: 'new_post'
  get 'univs/:id/search' => 'posts#search', as: 'search_post'
  get 'univs/:id/search/:subject' => 'posts#search', as: 'filter_post'
  resources :univs
  devise_for :users
  resources :comments
  resources :posts, except: [:new, :index]

  get 'users/:id' => 'users#show', as: 'user'
  get 'users' => 'users#mypage', as: 'mypage'

  post   '/comment_likes/:comment_id' => 'comment_likes#like_comment',   as: 'like_comment'
  delete '/comment_likes/:comment_id' => 'comment_likes#unlike_comment', as: 'unlike_comment'

  post   '/post_likes/:post_id' => 'post_likes#like_post',   as: 'like_post'
  delete '/post_likes/:post_id' => 'post_likes#unlike_post', as: 'unlike_post'

  delete '/layouts/:id' => 'messages#delete_message', as: 'delete_message'

  root 'univs#index'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :comment
  belongs_to :user
  belongs_to :post
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_comment_links.html.erb
<% if user_signed_in? %>
    <div class="like-comment-link" id="like-comment-link-<%= comment.id %>">

      <% if current_user.likes.find_by(comment_id: comment.id) #TODO この条件で大丈夫か %>
        <%= link_to unlike_comment_path(comment.id), method: :delete, remote: true do %>
        <div class="glyphicon glyphicon-heart" id="comment-heart-<%= comment.id %>">
          <%= comment.likes.count.to_s %>
        </div>
        <% end %>
      <% else %>
        <%= link_to like_comment_path(comment.id), method: :post, remote: true do %>
        <div class="glyphicon glyphicon-heart-empty" id="comment-heart-<%= comment.id %>">
          <%= comment.likes.count.to_s %>
        </div>
        <% end %>
      <% end %>
    </div>

<% else %>
  <div class="glyphicon glyphicon-heart-empty" >
    <%= comment.likes.count.to_s %>
<% end %>

app/views/likes/_like_post_links.html.erb
<% if user_signed_in? %>
    <div class="like-post-link" id="like-post-link-<%= post.id %>">
      <% if current_user.likes.find_by(post_id: post.id) #TODO この条件で大丈夫か %>
        <%= link_to unlike_post_path(post.id), method: :delete, remote: true do %>
        <div class="glyphicon glyphicon-heart" id="post-heart-<%= post.id %>"></div>
        <% end %>
      <% else %>
        <%= link_to like_post_path(post.id), method: :post, remote: true do %>
        <div class="glyphicon glyphicon-heart-empty" id="post-heart-<%= post.id %>">
          <%= post.likes.count.to_s %>
        </div>
        <% end %>
      <% end %>
    </div>
<% else %>
  <div class="glyphicon glyphicon-heart-empty" >
    <%= post.likes.count.to_s %>
  </div>
<% end %>

app/views/likes/like_post.js.erb
$("<%= @id_post_name %>").html('<%= escape_javascript(render("likes/like_post_links", post: @post  )) %>');
$("<%= @id_post_heart %>").removeClass('glyphicon-heart-empty');
$("<%= @id_post_heart %>").addClass('glyphicon-heart');

app/views/likes/unlike_post.js.erb
$("<%= @id_post_name %>").html('<%= escape_javascript(render("likes/like_post_links", post: @post  )) %>');
$("<%= @id_post_heart %>").addClass('glyphicon-heart-empty');
$("<%= @id_post_heart %>").removeClass('glyphicon-heart');