config/routes.rb
Rails.application.routes.draw do
  get 'univs/search', as: 'search_univs'
  get 'univs/:id/new' => 'posts#new', as: 'new_post'
  get 'univs/:id/search' => 'posts#search', as: 'search_post'
  get 'univs/:id/search/:subject' => 'posts#search', as: 'filter_post'
  resources :univs
  devise_for :users
  resources :comments
  resources :posts, except: [:new, :index]

  get 'users/:id' => 'users#show', as: 'user'
  get 'users' => 'users#mypage', as: 'mypage'

  post   '/comment_likes/:comment_id' => 'comment_likes#like_comment',   as: 'like_comment'
  delete '/comment_likes/:comment_id' => 'comment_likes#unlike_comment', as: 'unlike_comment'

  post   '/post_likes/:post_id' => 'post_likes#like_post',   as: 'like_post'
  delete '/post_likes/:post_id' => 'post_likes#unlike_post', as: 'unlike_post'

  delete '/layouts/:id' => 'messages#delete_message', as: 'delete_message'

  root 'univs#index'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/univ.rb
class Univ < ApplicationRecord
  has_many :posts
end

app/controllers/univs_controller.rb
class UnivsController < ApplicationController
  before_action :set_univ, only: [:show, :edit, :update, :destroy]

  # GET /univs
  # GET /univs.json
  # 大学検索画面（トップページ）
  def index
    @q = Univ.ransack(params[:q])
    @univs = @q.result
  end

  # 大学検索結果
  def search
    @q = Univ.ransack(params[:q])
    @univs = @q.result
    @query = params[:q][:name_cont]
  end

  # GET /univs/1
  # GET /univs/1.json
  # 大学トップページ
  def show
    @q = @univ.posts.ransack(params[:q])
    @posts = @univ.posts.order('created_at DESC')
    @subjects = @univ.posts.pluck(:subject).uniq
  end

  # GET /univs/new
  def new
    @univ = Univ.new
  end

  # GET /univs/1/edit
  def edit
  end

  # POST /univs
  # POST /univs.json
  def create
    @univ = Univ.new(univ_params)

    respond_to do |format|
      if @univ.save
        format.html { redirect_to @univ, notice: 'Univ was successfully created.' }
        format.json { render :show, status: :created, location: @univ }
      else
        format.html { render :new }
        format.json { render json: @univ.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /univs/1
  # PATCH/PUT /univs/1.json
  def update
    respond_to do |format|
      if @univ.update(univ_params)
        format.html { redirect_to @univ, notice: 'Univ was successfully updated.' }
        format.json { render :show, status: :ok, location: @univ }
      else
        format.html { render :edit }
        format.json { render json: @univ.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /univs/1
  # DELETE /univs/1.json
  def destroy
    @univ.destroy
    respond_to do |format|
      format.html { redirect_to univs_url, notice: 'Univ was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_univ
      @univ = Univ.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def univ_params
      params.require(:univ).permit(:name)
    end
end

app/helpers/univs_helper.rb
module UnivsHelper
end

app/views/univs/_form.html.erb
<%= form_with(model: univ, local: true) do |form| %>
  <% if univ.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(univ.errors.count, "error") %> prohibited this univ from being saved:</h2>

      <ul>
      <% univ.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :univ_name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/univs/edit.html.erb
<h1>Editing Univ</h1>

<%= render 'form', univ: @univ %>

<%= link_to 'Show', @univ %> |
<%= link_to 'Back', univs_path %>

app/views/univs/index.html.erb
<!-- /*<style>
  background:
    #fff
    url(top-background.jpg)
    no-repeat
    fixed
    center center;
  background-size: cover;
 </style>*/ -->
<h1 class="text-right"><small><%= Univ.all.size %>件の大学が登録されています</small></h1>

<br>
<%= image_tag 'icon.png'%>

<div class="row">
  <%= search_form_for @q, url:search_univs_path do |f| %>
  <div id="custom-search-input">
      <div class="input-group col-md-12">

          <%= f.search_field :name_cont, class: "search-query form-control", placeholder: "まずは大学名で検索!" %>
          <span class="input-group-btn">
          <%= f.button class: "btn btn-danger"  do %>
          <%= content_tag :span, "", class: "glyphicon glyphicon-search" %>
          <% end %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
	</div>
</div>

app/views/univs/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>大学新規登録</h1>

    <%= render 'form', univ: @univ %>
  </div>
</div>

app/views/univs/search.html.erb
<h1>
  <% if @query!='' %>
  <strong><%= @query%></strong>での<% end %>検索結果　　<small><%= @univs.all.size %>件の大学がヒットしました</small>
</h1>
<hr>
<% @univs.each do |univ|%>
  <p><%= link_to univ.name, univ_path(univ.id)%></p>
<% end %>
<hr>
<h3>あなたの大学が見つかりませんか？</h3>
<% if user_signed_in? %>
  <%= link_to '新しく大学を登録する', new_univ_path, class: 'btn btn-default' %>
<% else %>
  <p>ログインすることで新しく大学を登録できます</p>
  <%= link_to 'ログインする', new_user_session_path, class: 'btn btn-default' %>
<% end %>

app/views/univs/show.html.erb
<div class="box-max">
  <h1 style="float:left">
    <strong><%= @univ.name %></strong>
  </h1>
  <div style="float:right">
    <%= search_form_for @q, url:search_post_path, local: true, class: 'form-inline' do |f| %>
      <%= f.hidden_field :univ, value: @univ%>
      <%= f.search_field :subject_cont, class: "form-control input-sm", placeholder: '科目名で検索' %>  <%= f.submit "検索", class: "btn btn-default" %>
    <% end%>
  </div>
</div>
<div class="row" style="clear:both;">
  <div class="col-md-8 box-max">

    <br>
    <div class="box-max" style="clear:both;">
      <h2 style="float:left">最近の質問</h2>
      <div style="float:right">
        <% if user_signed_in? %>
          <%= link_to '質問する', new_post_path(@univ.id), class: 'btn btn-primary' %>
        <% end %>
      </div>　　　
    </div>　　　　　　　　　
    <hr>
    <% @posts.each do |post| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-style">
            <% if post.title.empty? %>
              <div>
                <h5 class="panel-title panel-head-title"><%= link_to post.body.truncate(10), post_path(post) %></h5>
              </div>
            <% else %>
              <div>
                <h5 class="panel-title panel-head-title"><%= link_to post.title.truncate(10), post_path(post) %></h5>
              </div>
            <% end %>
            <div class="panel-head-subject">
              <h5 class="panel-title"><%=post.subject%></h5>
            </div>
            <div class="panel-head-icon">
              <h5 class="panel-title">
                <i class="fa fa-comments" aria-hidden="true"></i>
                <strong><%=post.comments.size%></strong>件
              </h5>
            </div>
          </div>
        </div>
        <div class="panel-body">
         <div class="panel-style">
           <div class="panel-body-image">
             <div>
               <%= link_to image_tag(post.user.thumbnail, class: "img-thumbnail avatar"), user_path(post.user)%>
             </div>
             <div>
               <strong><%= link_to post.user.name, user_path(post.user.id) %></strong>
             </div>
           </div>
           <div class="panel-body-body">
             <p><%= post.body.truncate(50) %></p>
             <br>
             <p><small>投稿日時：<%= post.created_at %></small></p>
           </div>
         </div>
        </div>
      </div>
    <% end %>
    <%= link_to '大学情報を編集', edit_univ_path(@univ), class: 'btn btn-default' %>
    <br><br>
    </div>
    <div class="col-md-4">
      <br>
        <br><br><br><br><br><br><br>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h5 class="panel-title">登録科目一覧</h5>
          </div>
          <ul class="list-group">
          <% @subjects.each do |subject|%>
        	  <li class="list-group-item"><%= link_to subject, filter_post_path(@univ.id, subject) %></li>
          <% end %>
          </ul>
        </div>
    </div>
  </div>