config/routes.rb
Rails.application.routes.draw do
  get 'univs/search', as: 'search_univs'
  get 'univs/:id/new' => 'posts#new', as: 'new_post'
  get 'univs/:id/search' => 'posts#search', as: 'search_post'
  get 'univs/:id/search/:subject' => 'posts#search', as: 'filter_post'
  resources :univs
  devise_for :users
  resources :comments
  resources :posts, except: [:new, :index]

  get 'users/:id' => 'users#show', as: 'user'
  get 'users' => 'users#mypage', as: 'mypage'

  post   '/comment_likes/:comment_id' => 'comment_likes#like_comment',   as: 'like_comment'
  delete '/comment_likes/:comment_id' => 'comment_likes#unlike_comment', as: 'unlike_comment'

  post   '/post_likes/:post_id' => 'post_likes#like_post',   as: 'like_post'
  delete '/post_likes/:post_id' => 'post_likes#unlike_post', as: 'unlike_post'

  delete '/layouts/:id' => 'messages#delete_message', as: 'delete_message'

  root 'univs#index'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :univ
  has_many :comments
  has_many :likes
  has_many :messages

  validates :title,  presence: true, length: {maximum: 20}
  validates :body,  presence: true, length: {maximum: 2000}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def search
    univ = Univ.find(params[:id])
    @q = univ.posts.ransack(params[:q])
    @posts = @q.result
    if params[:q]
      @query = params[:q][:subject_cont]
    elsif params[:subject]
      @query = params[:subject]
      @posts = univ.posts.where(subject: @query)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @komento = Comment.where(post_id: params[:id])
    @comments = @post.comments
    @comment = Comment.new(post_id: @post.id, user_id: current_user.try(:id))
    @is_own_post = false
    if user_signed_in?
      @like = Like.where(user_id: current_user.id)
      if @post.user.id == current_user.id
        @is_own_post = true
      end
    end
  end

  # GET /posts/new
  def new
    # univ = Univ.find()
    @post = Post.new(univ_id: params[:id], user_id:current_user.id)
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to univ_path(@post.univ_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :univ_id, :subject, :body, :title)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, id: :post_user_id %>
  <%= form.hidden_field :univ_id, id: :post_univ_id %>

  <div class="form-group">
    <%= form.label :subject %>
    <%= form.text_field :subject, id: :post_subject, required: 'required', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body, required: 'required', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<%= render 'post_likes/like_post_links', post: post %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>質問を編集</h1>
    <%= render 'form', post: @post %>
    <%= link_to '質問を削除', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' } %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>新しく質問する</h1>
    <%= render 'form', post: @post %>
  </div>
</div>

app/views/posts/search.html.erb
<h1>
  <% if @query!='' %>
    <strong><%= @query%></strong>での<% end %>検索結果　　<small><%= @posts.all.size %>件の質問がヒットしました</small>
</h1>
<hr>

<% @posts.each do |post| %>
  <div class="panel panel-default">
    <div class="panel-heading">
     <h5 class="panel-title"><%= link_to post.title, post_path(post) %> 　　（ <%=post.subject%> ）</h5>
    </div>
    <div class="panel-body">
     <div class="row">
       <div class="col-md-1">
         <%= link_to image_tag(post.user.thumbnail, class: "img-thumbnail", size: '60x60'), user_path(post.user)%>
         <strong><%= link_to post.user.name, user_path(post.user.id) %></strong>
       </div>
       <div class="col-md-11">
         <p><%= post.body %></p>
         <br>
         <p><small>投稿日時：<%= post.created_at %></small></p>
       </div>
     </div>
    </div>
  </div>
  <hr>
<% end %>

app/views/posts/show.html.erb
<h1><%= link_to @post.univ.name, @post.univ, class: ''%></h1>
<hr>
<br><br>

<!-- <div class="p-bottom"> -->

<!-- 質問 -->
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-style">
      <h3 class="panel-title panel-head-title">
        <%= @post.title %>
      </h3>
      <h4 class="panel-head-subject">
        <%=@post.subject%>
      </h4>
      <div class="panel-head-icon">
        <% if @is_own_post%>
          <%= link_to '質問を編集', edit_post_path(@post), class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="panel-style">
      <div class="panel-body-image">
        <div>
          <% if @post.user.image.present? %>
            <%= link_to image_tag(@post.user.image.to_s, class: "img-thumbnail avatar"), user_path(@post.user) %>
          <% else %>
            <%= link_to image_tag(@post.user.thumbnail, class: "img-thumbnail avatar"), user_path(@post.user) %>
          <% end %>
        </div>
        <div>
          <strong><%= link_to @post.user.name, user_path(@post.user) %></strong>
        </div>
      </div>
      <div class="panel-body-body">
        <p><%= simple_format(@post.body) %></p>
      </div>
    </div>
    <hr>
    <div class="panel-style">
      <div class="panel-body-image">
        <a href="javascript:void(0)" onclick="show_block(); return false;">
          <i class="fa fa-reply fa-2x"></i>
        </a>
      </div>
      <div class="panel-fav">
        <%= render partial: 'posts/posts', locals: { post: @post } %>
      </div>
      <div class="panel-date">
        <%= @post.created_at %>
      </div>
    </div>
  </div>
</div>
<!-- 回答用フォーム -->
<div id="hoge" style="display: none">
  <div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">回答</h4>
  </div>
  <div class="panel-body">
    <div class="panel-style">
      <div class="panel-body-image">
        <% if user_signed_in? %>
          <div>
            <% if current_user.image.present? %>
              <%= link_to image_tag(current_user.image.to_s, class: "img-thumbnail avatar"), user_path(current_user)%>
            <% else %>
              <%= link_to image_tag(current_user.thumbnail, class: "img-thumbnail avatar"), user_path(current_user)%>
            <% end %>
          </div>
          <div>
            <strong><%= link_to current_user.try(:name), user_path(current_user)%></strong>
          </div>
        <% else %>
          <%= image_tag 'thumbnails/default.png', class: "img-thumbnail avatar" %>
        <p>
          <small>名無しさん</small>
        </p>
        <% end %>
      </div>
      <div class="panel-style">
        <%= form_with model: @comment, url: comments_path do |f| %>
          <%= f.hidden_field :post_id %>
          <%= f.hidden_field :user_id%>
          <div class="form-group">
            <%= f.label :body  %><br/>
            <%= f.text_field :body, class: "form-control" %>
          </div>
          <hr>
          <div class="panel-style">
            <div class="panel-body-image">
              <%= f.submit '回答を送信', class: "btn btn-default" %>
            </div>
            <div class="panel-body-body">
              <a href="" onclick="hide_block(); return false;" class="btn btn-default">フォームを閉じる</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
<hr>
<br>
<!-- 回答一覧 -->
<% @comments.each_with_index do |comment, i|%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">回答<%=i+1%></h4>
  </div>
  <div class="panel-body">
    <div class="panel-style">
      <div class="panel-body-image">
        <% if comment.user.nil? %>
          <div>
            <%= image_tag 'thumbnails/default.png', class: "img-thumbnail avatar" %>
            <small>名無しさん</small>
          </div>
        <% else %>
          <div>
            <div>
              <% if comment.user.image.present? %>
                <%= link_to image_tag(comment.user.image.to_s, class: "img-thumbnail avatar"), user_path(comment.user)%>
              <% else %>
                <%= link_to image_tag(comment.user.thumbnail, class: "img-thumbnail avatar"), user_path(comment.user)%>
              <% end %>
            </div>
            <strong><%= link_to comment.user.try(:name), user_path(comment.user)%></strong>
          </div>
        <% end %>
      </div>
      <div class="panel-body-body">
        <p><%= simple_format(comment.body) %></p>
      </div>
    </div>

    <hr>
    <div class="panel-style">
      <div class="panel-body-image">
      </div>
      <div class="panel-fav">
        <%= render partial: 'comments/comments', locals: { comment: @komento.find(comment.id) } %>
      </div>
      <div class="panel-date">
        <%= comment.created_at %>
      </div>
    </div>
  </div>
</div>
<% end%>